Fix payment additional information in case of credit card failure #188138869
r-martins/PagBank-Magento1 pull request #29
Opened 2024-08-25 00:39 UTC by ligiasalzano

2024-08-28 01:02 UTC, r-martins requested changes
Não funcionou pra mim.
Testei com cartão negado e depois com PIX, e ainda pude ver as parcelas e bandeira sendo exibidos junto ao QrCode no admin.

2024-08-28 19:50 UTC, ligiasalzano commented
@r-martins tentei replicar e o problema não aconteceu. Qual checkout você usou? Pela posição, eu tenho é no additional_data, nos testes aqui eu peguei o problema no addicional_information. Vou ver aqui.

2024-08-28 20:57 UTC, ligiasalzano commented
@r-martins, achei o problema. No OSC ele salva no add info as informações do cartão mesmo se não submeter o pedido. Se eu só preencho o cartão e depois troco pro Pix, ele salva. Fiz um ajuste para limpar os dados que começam com cc_ quando estiver usando pix ou boleto.

2024-08-29 03:49 UTC, r-martins approved these changes

2024-08-29 03:49 UTC, merged